package examples.jms;

/**
 * Represents a Loteria deck
 */
public enum LoteriaCard {
	EL_GALLO, EL_DIABLITO, LA_DAMA, EL_CATRIN, EL_PARAGUAS,
	LA_SIRENA, LA_ESCALERA, LA_BOTELLA, EL_BARRIL, EL_ARBOL,
	EL_MELON, EL_VALIENTE, EL_GORRITO, LA_MUERTE, LA_PERA,
	LA_BANDERA, EL_BANDOLON, EL_VILONCELLO, LA_GARZA, EL_PAJARO,
	LA_MANO, LA_BOTA, LA_LUNA, EL_COTORRO, EL_BORRACHO,
	EL_NEGRITO, EL_CORAZON, LA_SANDIA, EL_TAMBOR, EL_CAMARON,
	LAS_JARAS, EL_MUSICO, LA_ARAÑA, EL_SOLDADO, LA_ESTRELLA,
	EL_CAZO, EL_MUNDO, EL_APACHE, EL_NOPAL, EL_ALACRAN,
	LA_ROSA, LA_CALAVERA, LA_CAMPANA, EL_CANTARITO, EL_VENADO,
	EL_SOL, LA_CORONA, LA_CHALUPA, EL_PINO, EL_PESCADO,
	LA_PALMA, LA_MACETA, EL_ARPA, LA_RANA
}
